name: in_app_navigator
description: "The in_app_navigator Flutter library is a powerful tool designed to customize route navigation within your Flutter applications. It provides developers with an easy and flexible way to handle navigation actions such as push, pop, and other route management functionalities."
version: 1.0.2
repository: https://github.com/Mohiuddin655-PUB/flutter_in_app_navigator.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: